### ISSUE TITLE
Incompatibility with Statiq.Web beta 18

### ISSUE THREAD

**Issue by petrsvihlik** [alanta/Kontent.Statiq#29]
**Describe the bug**
The latest Statiq.Web depends on Statiq.Common v32 whereas Kontent.Statiq depends on v31. There are obviously some breaking changes which cause the combination of the latest versions not to work.

**To Reproduce**
Add `<PackageReference Include="Statiq.Web" Version="1.0.0-beta.18" />` to your project and you'll start getting errors.

I tried to upgrade this site for instance: https://github.com/Kentico/statiq-starter-kontent-lumen

**Expected behavior**
- build passes

**Actual behavior**
>[CRIT] Method not found: 'System.Threading.Tasks.Task`1<Statiq.Common.IDocument> Statiq.Common.IExecutionContextCreateDocumentFromStringExtensions.CreateDocumentAsync(Statiq.Common.IExecutionContext, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Object>>, System.String, System.String)'.

**Environment(please complete the following information):**
 - OS: Win
 - .NET 5
- beta 9

**Solution**
Upgrade the following references

https://github.com/alanta/Kontent.Statiq/blob/7a2f45ebff57e4d4c695a5e18bbe6c8b779b753b/Kontent.Statiq/Kontent.Statiq.csproj#L37-L38

to beta 32.

**Comment by daveaglick** [comment]
Yeah, sorry about that 😬. I generally try to keep breaks to a minimum at this point, especially with the more public surface area. In this case, I did some heavy work refactoring how content is handled to give a nice performance boost, but ended up refactoring out the need for async treatment of string content. Since async adds a performance overhead of it's own, I decided it was best going forward to consolidate all the content extensions on the same non-async signature to ease discovery.

In any case, the reaction after update should be straightforward - basically wherever it complains about a `FooAsync()` method, change it to `Foo()`. Let me know if you need a hand with the update!

I'll continue to try and keep breaks few and far between, but it's one of the reasons I haven't gone totally 1.0 yet. I expect there might be a handful more as I start to finish out Statiq Docs.

**Comment by alanta** [comment]
@daveaglick np, the fix is simple enough :) Thanks for the explanation.

**Comment by petrsvihlik** [comment]
thx for the quick release ;)
